name: flutter_backtome
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Esto es para el Icon
#dev_dependencies: 
#  flutter_launcher_icons: ""

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^2.0.0
  image_picker: ^1.1.2 #Selector de Imagenes

  english_words: ^4.0.0
  provider: ^6.0.0
  # Dependencias de Firebase
  firebase_core: ^3.6.0   # Firebase en general
  cloud_firestore: ^5.4.4 # Servicio de la base de datos
  firebase_auth: ^5.3.1   # Servicio de Autenticación
  fluttertoast: ^8.2.8    # ???

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "./lib/resources/logo_v2.png"

flutter:
  uses-material-design: true
  assets:
  - ./lib/resources/ITVer_Logo.png
  - ./lib/resources/itver_logo_sf.png
  - ./assets/mario.jpg
  - ./assets/ipone.jpg
